### ISSUE TITLE
`Cannot read properties of undefined (reading '0')` on newer Node.js versions

### ISSUE THREAD

**Issue by legobeat** [LavaMoat/LavaMoat#1211]
There is a known regression affecting Node.js versions >= `20.15.0` and >= `22.2.0`, resulting in unhandled runtime errors:

<details>

https://github.com/LavaMoat/LavaMoat/actions/runs/9816323753/job/27106390352#step:7:339

```npm exec lavamoat -- /home/runner/work/LavaMoat/LavaMoat/packages/browserify/test/fixtures/secureBundling/build.js --policyPath /home/runner/work/LavaMoat/LavaMoat/packages/browserify/test/fixtures/secureBundling/lavamoat/node/policy.json
(TypeError#1)
TypeError#1: Cannot read properties of undefined (reading '0')
  at isInsideNodeModules (node:internal/util:508:17)
  at showFlaggedDeprecation (node:buffer:178:8)
  at new Buffer (node:buffer:266:3)
  at new Buffer (LavaMoat/core/kernel:591:22)
  at new Buffer (LavaMoat/core/kernel:591:22)
  at new Buffer (LavaMoat/core/kernel:591:22)
  at decodeBase64 (/home/runner/work/LavaMoat/LavaMoat/node_modules/combine-source-map/node_modules/convert-source-map/index.js:13:10)
  at new Converter (/home/runner/work/LavaMoat/LavaMoat/node_modules/combine-source-map/node_modules/convert-source-map/index.js:42:28)
  at exports.fromComment (/home/runner/work/LavaMoat/LavaMoat/node_modules/combine-source-map/node_modules/convert-source-map/index.js:109:10)
  at exports.fromSource (/home/runner/work/LavaMoat/LavaMoat/node_modules/combine-source-map/node_modules/convert-source-map/index.js:125:22)
```

</details>

This affects `lavamoat-core` and dependencies. `@lavamoat/allow-scripts` is unaffected.

#### Related

- Upstream issue: https://github.com/nodejs/node/issues/53075
- #1184

**Comment by legobeat** [comment]
- #1251
