### ISSUE TITLE
allow-scripts - bug/feature: Support policies for optionalDependencies

### ISSUE THREAD

**Issue by rekmarks** [LavaMoat/LavaMoat#167]
`allow-scripts auto` should support the existence of `optionalDependencies` that aren't present. We recently ran into a problem with this on the MetaMask extension that forced us to do this: https://github.com/MetaMask/metamask-extension/pull/10375

Basically, `fsevents` is optional and not included on e.g. Linux, but is included in macOS. So, you get different policy files if you run it on Linux vs macOS. This is a problematic inconsistency for the extension team.

**Comment by kumavis** [comment]
this was fixed maybe in 1.0.1

**Comment by kumavis** [comment]
erik sez still present on 1.0.3

**Comment by kumavis** [comment]
oh yeah during auto

**Comment by lienpeng-390** [comment]
An error occurred while executing this command.

Error message:
running lifecycle scripts for event "postinstall"
- geckodriver
Error: command failed
    at ChildProcess.<anonymous> (/Users/lienpeng/metamask-extension/node_modules/@npmcli/promise-spawn/index.js:64:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  cmd: 'sh',
  args: [ '-c', 'node index.js' ],
  code: 1,
  signal: null,
  stdout: 'Downloading geckodriver... ',
  stderr: '\n' +
    'events.js:292\n' +
    "      throw er; // Unhandled 'error' event\n" +
    '      ^\n' +
    'ErrorClass [RequestError]: connect ETIMEDOUT 192.30.253.112:443\n' +
    '    at ClientRequest.<anonymous> (/Users/lienpeng/metamask-extension/node_modules/geckodriver/node_modules/got/index.js:69:21)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    at ClientRequest.emit (events.js:315:20)\n' +
    '    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n' +
    '    at TLSSocket.emit (events.js:315:20)\n' +
    '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
    '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n' +
    "Emitted 'error' event on DuplexWrapper instance at:\n" +
    '    at EventEmitter.emit (events.js:315:20)\n' +
    '    at ClientRequest.<anonymous> (/Users/lienpeng/metamask-extension/node_modules/geckodriver/node_modules/got/index.js:69:7)\n' +
    '    at Object.onceWrapper (events.js:422:26)\n' +
    '    [... lines matching original stack trace ...]\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:80:21) {\n' +
    "  code: 'ETIMEDOUT',\n" +
    "  host: 'github.com',\n" +
    "  hostname: 'github.com',\n" +
    "  method: 'GET',\n" +
    "  path: '/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-macos.tar.gz'\n" +
    '}\n',
  event: 'postinstall',
  script: 'node index.js',
  pkgid: 'geckodriver@1.21.0',
  path: 'node_modules/geckodriver'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
