### ISSUE TITLE
`allow-scripts` fails for dependencies installed from tarballs

### ISSUE THREAD

**Issue by rekmarks** [LavaMoat/LavaMoat#261]
On running `yarn allow-scripts` in [MetaMask/metamask-extension](https://github.com/MetaMask/metamask-extension) with the package `@metamask/snap-controllers` installed from the local tarball `metamask-snap-controllers-0.2.2.tgz`, I encounter the following error:

```text
TypeError [ERR_INVALID_URL]: Invalid URL: ./metamask-snap-controllers-0.2.2.tgz#00fe96aacbe7a0cac1c5aa680fb37ce782dc37cd
    at onParseError (internal/url.js:258:9)
    at new URL (internal/url.js:334:5)
    at getCanonicalNameInfo (.../metamask-extension/node_modules/@lavamoat/allow-scripts/src/index.js:192:15)
    at getCanonicalNameInfoForTreeNode (.../metamask-extension/node_modules/@lavamoat/allow-scripts/src/index.js:351:12)
    at loadAllPackageConfigurations (.../metamask-extension/node_modules/@lavamoat/allow-scripts/src/index.js:372:31)
    at async runAllowedPackages (.../metamask-extension/node_modules/@lavamoat/allow-scripts/src/index.js:29:7)
    at async start (.../metamask-extension/node_modules/@lavamoat/allow-scripts/src/cli.js:19:7) {
  input: './metamask-snap-controllers-0.2.2.tgz#00fe96aacbe7a0cac1c5aa680fb37ce782dc37cd',
  code: 'ERR_INVALID_URL'
}
```

**Comment by tmpfs** [comment]
It appears this is due to a missing scheme for the `URL` which is not included in `node.resolved`.

@kumavis, I think a hack like this should workaround the issue:

```javascript
let resolved = node.resolved;
if (resolved) {
  if (!/^(file|git|https?):/.test(resolved)) {
    resolved = `file:${resolved}`;
  }
  return getCanonicalNameInfo(resolved)
}
```

To replace https://github.com/LavaMoat/LavaMoat/blob/main/packages/allow-scripts/src/index.js#L350-L352
