### ISSUE TITLE
Error: LavaMoat - required package not in allowlist: package "gulp-livereload>chalk>ansi-styles>color-convert"

### ISSUE THREAD

**Issue by th0masi** [LavaMoat/lavamoat#754]
During the build process of the MetaMask project, when running `yarn dist`, I encounter the following error. How can I resolve this?

Additionally, I've attempted to build the project using `yarn start`, but it continuously hangs.

Use `yarn dist`:
```
C:\Users\Jonghi\Desktop\metamask-extension>yarn dist
Error: LavaMoat - required package not in allowlist: package "gulp-livereload>chalk>ansi-styles>color-convert" requested "gulp-livereload>chalk>ansi-styles>color-convert>color-name" as "color-name"
  at requireRelative (LavaMoat/core/kernel:828:15)
  at requireRelativeWithContext (LavaMoat/core/kernel:774:18)
  at Object.eval (C:\Users\Jonghi\Desktop\metamask-extension\node_modules\gulp-livereload\node_modules\color-convert\conversions.js:3:19)
  at internalRequire (LavaMoat/core/kernel:761:27)
  at requireRelative (LavaMoat/core/kernel:806:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:774:18)
  at Object.eval (C:\Users\Jonghi\Desktop\metamask-extension\node_modules\gulp-livereload\node_modules\color-convert\index.js:2:19)
  at internalRequire (LavaMoat/core/kernel:761:27)
  at requireRelative (LavaMoat/core/kernel:806:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:774:18)
```

Use `yarn start` (Waited more than an hour): 
```
C:\Users\Jonghi\Desktop\metamask-extension>yarn start
Building lavamoat runtime file (scuttling is off)
Running task "dev"...
Starting 'dev'...
Starting 'clean'...
Finished 'clean'
Starting 'styles:dev'...
Finished 'styles:dev'
Starting 'scripts:core:dev:standardEntryPoints'...
Starting 'scripts:core:dev:contentscript'...
Starting 'scripts:core:dev:disable-console'...
Starting 'scripts:core:dev:sentry'...
Starting 'static:dev'...
Starting 'manifest:dev'...
Starting 'reload'...
Finished 'reload'
Finished 'manifest:dev'
Finished 'static:dev'
scripts:core:dev:disable-console: Bundle start: "disable-console"
scripts:core:dev:sentry: Bundle start: "sentry-install"
scripts:core:dev:contentscript: Bundle start: "inpage"
scripts:core:dev:disable-console: Bundle end: "disable-console"
scripts:core:dev:standardEntryPoints: Bundle start: "primary"
scripts:core:dev:contentscript: Bundle end: "inpage"
scripts:core:dev:contentscript: Bundle start: "contentscript"
scripts:core:dev:sentry: Bundle end: "sentry-install"
scripts:core:dev:contentscript: Bundle end: "contentscript"
scripts:core:dev:standardEntryPoints: Bundle end: "primary"
^C^C^C
```

**Comment by boneskull** [comment]
Have you tried rebuilding the policy?

**Comment by naugtur** [comment]
Let's do this over slack in `#lavamoat` channel instead.
