### ISSUE TITLE
Problem running Lavamoat with MetaMask build system

### ISSUE THREAD

**Issue by EtDu** [LavaMoat/LavaMoat#96]
```
LavaMoat generating config from entry "/Users/Etienne/Desktop/metamask-stuff/metamask-extension/development/build/index.js"...
Error: Cannot find module './is-implemented'
Require stack:
- /Users/Etienne/Desktop/metamask-stuff/metamask-extension/node_modules/es5-ext/string/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at resolve (internal/modules/cjs/helpers.js:80:19)
    at /Users/Etienne/.npm/_npx/7851/lib/node_modules/lavamoat/src/parseForConfig.js:48:18
    at /Users/Etienne/.npm/_npx/7851/lib/node_modules/lavamoat/src/parseForConfig.js:128:20
    at Array.map (<anonymous>)
    at makeJsModuleRecord (/Users/Etienne/.npm/_npx/7851/lib/node_modules/lavamoat/src/parseForConfig.js:124:53)
    at async walk (/Users/Etienne/.npm/_npx/7851/lib/node_modules/lavamoat/node_modules/lavamoat-core/src/walk.js:14:24)
    at async /Users/Etienne/.npm/_npx/7851/lib/node_modules/lavamoat/node_modules/lavamoat-core/src/walk.js:27:5
    at async Promise.all (index 3)
    at async walk (/Users/Etienne/.npm/_npx/7851/lib/node_modules/lavamoat/node_modules/lavamoat-core/src/walk.js:18:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Etienne/Desktop/metamask-stuff/metamask-extension/node_modules/es5-ext/string/noop.js'
  ]
}
```

**Comment by EtDu** [comment]
Running Node v12+

**Comment by kumavis** [comment]
this was resolved at some point
